version: '3'
services:
  #Mongo
  mongo:
    image: mongo
    container_name: mongo-gps
    restart: always
    volumes:
      - .db:/var/lib/mongodb
    ports:
      - "27017:27017"
    networks:
      - gps-network
  #GPS Server - node.js
  gps-server:
    image: node:12
    container_name: gps-server
    volumes:
      - .:/home/node/app
    ports:
      - "6666:6666"
      - "8008:8008"
    networks:
      - gps-network
    working_dir: /home/node/app
    command: npm start
##Docker Networks
networks:
  gps-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local